name: ⚡ Delete sourcemaps

on:
  delete:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  actions: write
  contents: read

jobs:
  sourcemaps-deletion:
    name: ⚙️ Delete sourcemaps
    runs-on: ubuntu-latest
    if: "startsWith(github.event.ref_type, 'branch')"
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@ecf28ddc73e819eb6fa29df6b34ef8921c743461 # v2.1.3
        with:
          bun-version: latest

      - name: ⎔ Setup node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.node-version'
          # cache: 'bun'
          cache-dependency-path: ./package.json

      - name: 📥 Install deps
        run: bun install --frozen-lockfile

      - name: 📡 delete-sourcemap
        env:
          DELETED_BRANCH: ${{ github.event.ref }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          R2_DOCUMENTS_ACCESS_KEY_ID: ${{ secrets.R2_DOCUMENTS_ACCESS_KEY_ID }}
          R2_DOCUMENTS_SECRET_ACCESS_KEY: ${{ secrets.R2_DOCUMENTS_SECRET_ACCESS_KEY }}
        run: bun run delete-sourcemaps